<a href="https://colab.research.google.com/github/vivekdevims/Python_Assignment/blob/main/NumPy_Practice_40Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Questions

**Instructions:** Dear Students Each question is self‑explanatory. Read the markdown prompt and write the code in the cell below it where marked `# answer here`. Keep solutions simple and focused on the asked concept.

- Q1–Q30: Single-topic questions in sequence (basics → indexing → operations → aggregations → reshaping/broadcasting → utilities).

- Q31–Q35: Multi‑concept (combine 2–3 ideas you practiced).

- Q36–Q40: Use a single dataset loaded via **pandas** and perform **NumPy** operations on it. The file `students_scores.csv` is already available in the same folder as this notebook.


### Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.

In [2]:
# The original code had an error in creating a 2D array.
# This code should be in a later question about 2D arrays.
# For now, I will provide the code for Q1.
# Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# answer here
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print(a.ndim)

(2, 3)
2


### Q2. Create a 2D NumPy array from `[[1, 2, 3], [4, 5, 6]]` and print its `shape` and `ndim`.

In [4]:
aa=np.array([[1,2,3],[4,5,6]])
aa

array([[1, 2, 3],
       [4, 5, 6]])

### Q3. Create an array of 6 zeros and print it.

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

### Q4. Create an array of 5 ones (float) and print it.

In [6]:
q=np.ones(5).astype(float)
q.dtype

dtype('float64')

### Q5. Use `np.arange` to create an array from 2 to 14 (inclusive of 2, exclusive of 14) with a step of 2 and print it.

In [7]:
a=np.arange(2,14,2)
a

array([ 2,  4,  6,  8, 10, 12])

In [8]:
# answer here

### Q6. Use `np.linspace` to create 5 evenly spaced values from 0 to 1 and print them.

In [9]:
a=np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Q7. Create an integer array `[10, 20, 30]` then convert it to `float` dtype and print both arrays.

In [10]:
a=np.array([10,20,30,40]).astype(float)
aa=np.array([10,20,30,40])
print(a)
print(aa)

[10. 20. 30. 40.]
[10 20 30 40]


### Q8. Create an array of 12 numbers from 0 to 11 and reshape it to `3x4`; print the reshaped array.

In [11]:
a=np.array([0,1,2,3,4,5,6,7,8,9,10,11]).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Q9. For the array `a = np.array([[1,2,3],[4,5,6]])`, print `a.shape`, `a.ndim`, and `a.size`.

In [12]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


### Q10. For the array `a = np.array([1,2,3], dtype=np.int32)`, print `a.dtype` and `a.itemsize`.

In [13]:
a=np.array([1,2,3],dtype=np.int32)
print(a.dtype)
print(a.itemsize)

int32
4


### Q11. Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, and the element at index 2.

In [14]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


### Q12. Given `arr = np.array([5, 10, 15, 20, 25])`, use negative indexing to print the last two elements.

In [15]:
a=np.array([5,6,7,8,9])
print(a[-2])

8


### Q13. Given `arr = np.array([0,1,2,3,4,5,6,7,8,9])`, print the slice from index 2 to 7 (exclusive).

In [16]:
arr=np.array([0,1,3,4,5,6,7,8,9])

### Q14. Given `m = np.arange(1,13).reshape(3,4)`, print the second row and the third column (as 1D slices).

In [17]:
ab=np.arange(1,13).reshape(3,4)
display(ab[1:2,2:3])

array([[7]])

### Q15. Given `m = np.arange(1,13).reshape(3,4)`, print the submatrix containing rows 0 to 1 and columns 1 to 3.

In [18]:
m=np.arange(1,13).reshape(3,4)
display(m[0:2,1:3])

array([[2, 3],
       [6, 7]])

### Q16. Given `arr = np.arange(1,11)`, create a boolean mask for even numbers and print the even elements.

In [19]:
m=np.arange(1,11)
m[m%2==0]

array([ 2,  4,  6,  8, 10])

### Q17. Given `arr = np.arange(1,11)`, set all odd elements to `-1` (modify in place) and print the result.

In [20]:
a=np.arange(1,11)
a[a%2!=0]=-1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

### Q18. Given `arr = np.array([1,2,3])`, add `5` to every element and print the result (element‑wise).

In [21]:
ar=np.array([1,2,3])
ar+5
display(ar+5)

array([6, 7, 8])

### Q19. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, print `a + b` and `a * b` (element‑wise).

In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
display(a+b)
display(a*b)

array([5, 7, 9])

array([ 4, 10, 18])

### Q20. Given `a = np.array([1,2,3])` and `b = np.array([[10],[20],[30]])`, use broadcasting to compute `a + b` and print it.

In [23]:
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
display(a+b)

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

### Q21. Given `arr = np.array([3, 7, 2, 9, 5])`, print its `sum`, `mean`, `min`, and `max`.

In [24]:
arr=np.array([3,7,2,9,5])
display(arr.sum())
display(arr.mean())
display(arr.min())
display(arr.max())

np.int64(26)

np.float64(5.2)

np.int64(2)

np.int64(9)

### Q22. Given `m = np.arange(1,13).reshape(3,4)`, print the sum along axis 0 and along axis 1.

In [25]:
m=np.arange(1,13).reshape(3,4)
display(m.sum(axis=0))
display(m.sum(axis=1))

array([15, 18, 21, 24])

array([10, 26, 42])

### Q23. Given `arr = np.array([10, 20, 5, 40, 25])`, print the indices of the `max` and `min` elements using `np.argmax` and `np.argmin`.

In [26]:
arr=np.array([10,20,5,40,25])
display(arr.argmax())
display(arr.argmin())

np.int64(3)

np.int64(2)

### Q24. Given `arr = np.array([3, 3, 1, 2, 2, 2, 5])`, print the sorted array and the unique values using `np.unique`.

In [27]:
arr=np.array([3,3,1,2,2,4,5,4])
display(np.sort(arr))
display(np.unique(arr))

array([1, 2, 2, 3, 3, 4, 4, 5])

array([1, 2, 3, 4, 5])

### Q25. Given `arr = np.array([9, 1, 5, 3, 7])`, sort it in ascending order and print the result (do not modify original).

In [28]:
arr=np.array([9,1,5,3,7])
display(np.sort(arr))
display(arr)


array([1, 3, 5, 7, 9])

array([9, 1, 5, 3, 7])

### Q26. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, horizontally concatenate them and print the result.

In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])
display(np.hstack((a,b)))
display(np.concat((a,b),axis=0))
display(np.vstack((a,b)))

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

### Q27. Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, stack them vertically and print the result.

In [46]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
display(np.vstack((a,b)))
display(np.hstack(  (a,b)))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Q28. Given `arr = np.arange(1,13)`, split it into 3 equal parts and print each part.

In [31]:
app=np.arange(1,13)
display(np.split(app,3))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

### Q29. Set a random seed (e.g., 42), generate 5 random integers from 0 to 9 using `np.random.randint`, and print them.

In [32]:

random_integers = np.random.randint(0, 10, 5)
display(random_integers)


array([1, 6, 3, 8, 3])

### Q30. Given `arr = np.array([-3, 1, -1, 4, -2, 5])`, use `np.where` to replace negative values with `0` and print the new array.

In [33]:
a=np.array([-3,1,-1,4,-2,5])
display(np.where(a<0,0,a))

array([0, 1, 0, 4, 0, 5])

### Q31. Create a 3D array of shape `(2, 3, 4)` using `np.arange` then compute the mean along axis 2 and print the result.

In [34]:
a=np.arange(1,25).reshape(2,3,4)
display(a.mean(axis=2))

array([[ 2.5,  6.5, 10.5],
       [14.5, 18.5, 22.5]])

### Q32. Create an array from `[5, 10, 15, 20, 25]`, slice out `[10, 15, 20]`, then normalize that slice to range 0–1 using min‑max formula and print it.

In [35]:
a=np.array([5,10,15,20,25])
b=a[1:4]
display(b)
display((b-b.min())/(b.max()-b.min()) )



array([10, 15, 20])

array([0. , 0.5, 1. ])

### Q33. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`; compute the dot product and also form a `3x2` matrix from `a` and `b` and print both results.

In [45]:
a=np.array([1,2,3])
b=np.array([4,5,6])
aa=np.dot(a,b)
display(aa)
display(np.column_stack((a,b)))


np.int64(32)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# answer here

### Q34. Create an array of 12 values (1–12), reshape it to `3x4`, then count how many values are greater than `6` and print the count.

In [53]:
arr=np.arange(1,13).reshape(3,4)
display(arr)
display(arr[arr>6].size)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

6

### Q35. Create an array from 0–9; replace all odd numbers with `-1` *except* keep the first and last elements unchanged; print the final array.

In [54]:
a=np.arange(0,9)
a[a%2!=0]=-1
a[0]=0
a[-1]=9
display(a)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  9])

### Dataset for Q36–Q40

A CSV file **`students_scores.csv`** is already placed in this folder (Link-https://drive.google.com/file/d/1B7zDahhmQzXkQmvskS27H07B4Xftf9xA/view?usp=sharing).  

Columns: `id, math, english, science` (10 students). Use **pandas** to import the file and then perform **NumPy** operations.


### Q36. Import `students_scores.csv` as a pandas DataFrame `df`. Then convert the `math`, `english`, and `science` columns to separate NumPy arrays and print their shapes.

In [61]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/data_set/students_scores.csv")
d=np.array(df["math"])
e=np.array(df["english"])
s=np.array(df["science"])
display(d)
display(e)
display(s)

array([78, 56, 88, 45, 92, 67, 73, 59, 84, 61])

array([65, 70, 81, 55, 76, 62, 80, 58, 79, 69])

array([72, 60, 90, 48, 85, 71, 66, 64, 88, 57])

In [56]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Q37. Using NumPy on the arrays from Q36, compute the mean score of each subject (math, english, science) and print them.

In [63]:
display(d.mean())
display(e.mean())
display(s.mean())

np.float64(70.3)

np.float64(69.5)

np.float64(70.1)

### Q38. Using NumPy, compute each student’s **total score** (math + english + science) and print the `id` of the student with the highest total.

In [66]:
display(d+e+s)
display(np.argmax(d+e+s))

array([215, 186, 259, 148, 253, 200, 219, 181, 251, 187])

np.int64(2)

### Q39. Using NumPy, standardize the `math` scores to **z-scores**: `(x - mean) / std` and print the first 5 standardized values.

In [67]:
m=df['math'].values
score=(m-np.mean(m))/np.std(m)
print(score[:5])

[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


In [43]:
# this is how you can approach question number 39
# dont fear about std(standard deviation , just google it and you understand its simple, else you can connect for doubts)


import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("students_scores.csv")

# Extract math column as NumPy array
math_scores = df["math"].values

# Compute z-scores
z_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)

# Print first 5 standardized values
print(z_scores[:5])


FileNotFoundError: [Errno 2] No such file or directory: 'students_scores.csv'

### Q40. Using NumPy logical operations, count how many students scored **≥ 70 in all three subjects** and print that count.

In [75]:
c=df[(df['english']>=70)&(df['math']>=70)&(df['science']>=70)]
display(c)
count_great_than_70=df[(df['english']>=70)&(df['math']>=70)&(df['science']>=70)].shape[0]
display(count_great_than_70)


id  math  english  science
2  S03    88       81       90
4  S05    92       76       85
8  S09    84       79       88

3